version: "3.8"
services:
  postgis:
    image: "mdillon/postgis"
    ports:
      - "25432:5432"
    volumes:
      - YOUR_DATA_DIR/postgres_data/data:/var/lib/postgresql/data
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8280:8080"
    volumes:
      - YOUR_DATA_DIR/geoserver_data:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - SAMPLE_DATA=true

networks:
  default:
    external:
      name: gist604b
