version: "3.8"
services:
  postgis:
    image: "mdillon/postgis"
    ports:
      - "5432:5432"
    volumes:
      - /Users/aaryno/postgres_data:/var/lib/postgresql
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8080:8080"
    volumes:
      - /Users/aaryno/geoserver_data:/opt/geoserver/data_dir
    depends_on:
      - postgis
  populate:
    image: "aaryno/postgis-populate-osm"
    depends_on:
      - postgis
    deploy:
      replicas: 0
