version: "3.8"
services:
  postgis:
    image: "mdillon/postgis"
    ports:
      - "15432:5432"
    volumes:
      - YOUR_DATA_DIR/postgres_data/data:/var/lib/postgresql/data
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8280:8080"
    volumes:
      - YOUR_DATA_DIR/geoserver_data:/opt/geoserver/data_dir
    depends_on:
      - postgis

networks:
  default:
    external:
      name: gist604b
